import { CATALOG_KK } from '../data/catalogTranslationsKk';

/**
 * Translates Excel-sourced catalog text (product names, subcategories,
 * descriptions, free-text spec values) via the machine-translated lookup
 * map generated by scripts/translate-catalog.mjs. Falls back to the
 * original Russian text when no translation exists (missing key, or
 * lang is 'ru') — never throws, never shows a blank value.
 */
export function tc(text, lang) {
  if (!text || lang !== 'kk') return text;
  return CATALOG_KK[text] || text;
}
