// Machine-translates the Excel-sourced catalog text (product names,
// subcategory names, descriptions, and a few free-text spec values) from
// Russian to Kazakh via the unofficial Google Translate endpoint (no API
// key needed). Output is a flat { [russianText]: kazakhText } map consumed
// at runtime by src/i18n/translateCatalogText.js — the source data files
// under src/data/products/*.json are never modified.
//
// Quality note: this is machine translation of technical electrical-
// equipment nomenclature with no human review — acceptable for this
// project per an explicit, informed decision, but flagged here for anyone
// re-running it: spot-check a sample of the output before publishing.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(__dirname, '..');
const PRODUCTS_DIR = path.join(ROOT, 'src', 'data', 'products');
const OUTPUT_FILE = path.join(ROOT, 'src', 'data', 'catalogTranslationsKk.js');

const TRANSLATABLE_SPEC_LABELS = new Set(['Тип изоляторов, траверс, провода', 'Крепление на проводе', 'Комплектация']);

const NEWLINE_PLACEHOLDER = ' ¶ '; // pilcrow — vanishingly unlikely to collide with source text
const MAX_BATCH_CHARS = 1400;
const BATCH_DELAY_MS = 250;

function collectStrings() {
  const unique = new Set();
  const files = fs.readdirSync(PRODUCTS_DIR).filter((f) => f.endsWith('.json') && f !== 'index.json');
  for (const file of files) {
    const products = JSON.parse(fs.readFileSync(path.join(PRODUCTS_DIR, file), 'utf8'));
    for (const p of products) {
      if (p.name) unique.add(p.name);
      if (p.subcategoryName) unique.add(p.subcategoryName);
      if (p.description) unique.add(p.description);
      for (const [label, value] of Object.entries(p.specs || {})) {
        if (TRANSLATABLE_SPEC_LABELS.has(label) && value) unique.add(value);
      }
    }
  }
  return [...unique];
}

function buildBatches(strings) {
  const batches = [];
  let current = [];
  let currentChars = 0;
  for (const str of strings) {
    const len = str.length + 10;
    if (current.length && currentChars + len > MAX_BATCH_CHARS) {
      batches.push(current);
      current = [];
      currentChars = 0;
    }
    current.push(str);
    currentChars += len;
  }
  if (current.length) batches.push(current);
  return batches;
}

async function translateBatch(strings, attempt = 1) {
  const escaped = strings.map((s) => s.replace(/\n/g, NEWLINE_PLACEHOLDER));
  const text = escaped.join('\n');
  const url = `https://translate.googleapis.com/translate_a/single?client=gtx&sl=ru&tl=kk&dt=t&q=${encodeURIComponent(text)}`;

  let res;
  try {
    res = await fetch(url);
  } catch (err) {
    if (attempt >= 4) throw err;
    await new Promise((r) => setTimeout(r, 1000 * attempt));
    return translateBatch(strings, attempt + 1);
  }

  if (!res.ok) {
    if (attempt >= 4) throw new Error(`Translate request failed: ${res.status}`);
    await new Promise((r) => setTimeout(r, 1000 * attempt));
    return translateBatch(strings, attempt + 1);
  }

  const data = await res.json();
  const translatedBlob = data[0].map((seg) => seg[0]).join('');
  const translatedLines = translatedBlob.split('\n').map((s) => s.replace(new RegExp(NEWLINE_PLACEHOLDER.trim(), 'g'), '\n').trim());

  if (translatedLines.length !== strings.length) {
    throw new Error(`Batch line-count mismatch: sent ${strings.length}, got ${translatedLines.length}`);
  }
  return translatedLines;
}

async function main() {
  const strings = collectStrings();
  console.log(`Collected ${strings.length} unique strings to translate.`);

  const batches = buildBatches(strings);
  console.log(`Split into ${batches.length} batches.`);

  const map = {};
  let done = 0;
  for (const batch of batches) {
    const translated = await translateBatch(batch);
    batch.forEach((original, i) => {
      map[original] = translated[i];
    });
    done += batch.length;
    if (done % 500 < batch.length) console.log(`  ...${done}/${strings.length}`);
    await new Promise((r) => setTimeout(r, BATCH_DELAY_MS));
  }

  const header = `// Auto-generated by scripts/translate-catalog.mjs — do not edit by hand.\n// Machine-translated (Russian -> Kazakh) catalog text, no human review.\n// Run \`node scripts/translate-catalog.mjs\` to regenerate after re-importing the Excel catalog.\nexport const CATALOG_KK = `;
  fs.writeFileSync(OUTPUT_FILE, header + JSON.stringify(map, null, 2) + ';\n');
  console.log(`Wrote ${Object.keys(map).length} translations to ${path.relative(ROOT, OUTPUT_FILE)}`);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
